# Setup

In [ ]:
# !pip install topicgpt
# !pip install openai==0.28.1
# !pip install topicgpt

In [1]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/ngocdoan/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [37]:
import sys
sys.path.append('../')
import os
from dotenv import load_dotenv

load_dotenv()

True

# TwentyNewsgroups example

In [2]:
from sklearn.datasets import fetch_20newsgroups

data = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes')) #download the 20 Newsgroups dataset
corpus = data['data'] 

corpus = [doc for doc in corpus if doc != ""] #remove empty documents

In [ ]:
from topicgpt.TopicGPT import TopicGPT

tm = TopicGPT(
    openai_api_key = os.environ.get("DLAB_OPENAI_KEY"),
    n_topics = 20 # select 20 topics since the true number of topics is 20 
)

/Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages/numba/np/ufunc/dufunc.py:346: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
  warnings.warn(msg, errors.NumbaWarning)
/Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages/numba/np/ufunc/dufunc.py:346: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
  warnings.warn(msg, errors.NumbaWarning)
/Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages/numba/np/ufunc/dufunc.py:346: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
  warnings.warn(msg, errors.NumbaWarning)

In [4]:
tm.fit(corpus) # the corpus argument should be of type list[str] where each string represents one document

Removed 0 empty documents.
Computing vocabulary...

Processing corpus: 100%|██████████| 18466/18466 [00:14<00:00, 1296.33it/s]

Most common words in the vocabulary:
n't: 17116
would: 10872
one: 10144
people: 6442
like: 6409
get: 5815
know: 5742
also: 5588
use: 4987
think: 4982
Computing embeddings...

100%|██████████| 18466/18466 [00:02<00:00, 7558.73it/s]
  1%|          | 154/18466 [00:28<56:21,  5.42it/s]

KeyboardInterrupt:

(stopped because it's taking too long)

In [ ]:
print(tm.topic_lis)

# Our data (r/qanoncasualties)

In [4]:
import pandas as pd
df_post = pd.read_csv("../data/processed/posts_w_labels.csv")
df_post.head()

,author,created_utc,id,link_flair_text,num_comments,permalink,score,selftext,title,name,author_fullname,word_count,created_datetime,year,sentences_topics,sentences_labels,Label,sentences
0,Ok-Slide-9849,1701251429,186lthy,NaN,2,/r/QAnonCasualties/comments/186lthy/a_belated_...,4,\tI've known about this group for a while and ...,"A belated post, does the it ever end?",t3_186lthy,t2_o416vnkb,924,1701251429000,2023,"[68, -1, -1, 0, 270, -1, 70, -1, -1, -1, -1, -...",['Social Deterioration and Relationship Strain'],['Social Deterioration and Relationship Strain'],"[""\tI've known about this group for a while an..."
1,wanderingjeannie,1660010267,wjquol,NaN,3,/r/QAnonCasualties/comments/wjquol/q_anti_vax_...,13,\n\n\nDivorce is difficult situation generally...,Q anti Vax mom using the kids to hurt the Ex h...,t3_wjquol,t2_q75aaxj9,535,1660010267000,2022,"[-1, 42, 14, -1, -1, 188, 54, -1, -1, -1, -1, ...",['Social Deterioration and Relationship Strain...,['Social Deterioration and Relationship Strain...,"[""\n\n\nDivorce is difficult situation general..."
2,Mamailla,1611614013,l4zfzt,NaN,9,/r/QAnonCasualties/comments/l4zfzt/qanon_frien...,74,\n\n\nFive years ago when Trump began his camp...,Qanon friends sound like stories from Jonestown,t3_l4zfzt,t2_2yo216d6,236,1611614013000,2021,"[-1, 12, -1, -1, 2, -1, 44, 286]",['Social Deterioration and Relationship Strain'],['Social Deterioration and Relationship Strain'],['\n\n\nFive years ago when Trump began his ca...
3,getsomeyayas,1630144463,pd70my,NaN,5,/r/QAnonCasualties/comments/pd70my/i_think_im_...,17,"\n\n\nhi, just using my throwaway to rant a li...",i think i'm beginning to lose my uncle,t3_pd70my,t2_4gftpyni,521,1630144463000,2021,"[185, -1, -1, 350, 4, -1, -1, -1, -1, 212, -1,...","['Interpersonal Harm and Moral Disregard', 'As...","['Asian and Immigrant Family Dynamics', 'Inter...","['\n\n\nhi, just using my throwaway to rant a ..."
4,f_print,1597152737,i7rvmd,NaN,11,/r/QAnonCasualties/comments/i7rvmd/looking_for...,9,\n\n*Tl;dr What is the best source for Q-Anon....,Looking for best source of QAnon material to h...,t3_i7rvmd,t2_b7t0diw,383,1597152737000,2020,"[104, -1, 37, 37, -1, 139, -1, 397, 104, 73, -...",['Radical Ideological Alignment and Intoleranc...,"['COVID-19 Lockdowns', 'YouTube Algorithms', '...",['\n\n*Tl;dr\xa0What is the best source for Q-...

In [23]:
len(df_post)

12747

In [24]:
corpus_qan = df_post['selftext'] 

corpus_qan = [doc for doc in corpus_qan if doc != ""]

In [38]:
tm_qan = TopicGPT(
    openai_api_key = os.environ.get("DLAB_OPENAI_KEY"),
    corpus_instruction="The dataset consists of posts from r/QAnonCasualties subreddit, a forum where individuals share personal stories about their relatives' involvement in the QAnon conspiracy."
)

In [39]:
tm_qan.fit(corpus_qan)

Removed 0 empty documents.
Computing vocabulary...

Processing corpus: 100%|██████████| 12747/12747 [00:15<00:00, 814.33it/s]

Most common words in the vocabulary:
n't: 28618
like: 18161
people: 14652
know: 14451
would: 13104
get: 13047
mom: 11613
even: 11261
family: 10858
one: 10339
Computing embeddings...

100%|██████████| 12747/12747 [00:02<00:00, 5880.32it/s]
 41%|████▏     | 5278/12747 [16:51<23:32,  5.29it/s]

Error HTTP code 502 from API (<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>

<title> | 502: Bad gateway</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />
</head>
<body>
<div id="cf-wrapper">
    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
                <span class="inline-block">Bad gateway</span>
                <span class="code-label">Error code 502</span>
            </h1>
            <div>
                Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.openai.com" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2026-04-30 08:35:09 UTC</div>
        </header>
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                    <div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Browser

  </h3>

  <span class="leading-1.3 text-2xl text-green-success">Working</span>

</div>
                    <div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&#38;utm_campaign=api.openai.com" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Lyon</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
  <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.openai.com" target="_blank" rel="noopener noreferrer">
    Cloudflare
  </a>
  </h3>

  <span class="leading-1.3 text-2xl text-green-success">Working</span>

</div>
                    <div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">api.openai.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Host

  </h3>

  <span class="leading-1.3 text-2xl text-red-error">Error</span>

</div>
                </div>
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The web server reported a bad gateway error.</p>
                </div>
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                    <p class="mb-6">Please try again in a few minutes.</p>
                </div>
            </div>
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
    <p class="text-13">
      <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">9f4536228c68e7f3</strong></span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
      <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
        Your IP:
        <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
        <span class="hidden" id="cf-footer-ip">185.25.192.150</span>
        <span class="cf-footer-separator sm:hidden">&bull;</span>
      </span>
      <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&#38;utm_campaign=api.openai.com" id="brand_link" target="_blank">Cloudflare</a></span>

    </p>
    <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
  </div><!-- /.error-footer -->

    </div>
</div>
</body>
</html>) occured for chunk 0 of document 0
I was raised by parents who were registered Democrats and considered themselves fairly liberal.  They voted for Dems in every election as I was growing up. I was raised to be accepting of everyone and no person should be excluded from society no matter how different they looked or acted.

They voted for Clinton both terms and voted for Obama both terms.

It was halfway thru Obama's second term that I started to notice the change.  Fox News replaced the different news programs they watched (originally CNN, CBS, MSN, etc).  Soon they started rattling on about Obama not being American born and started agreeing with Tea Party buffoons.  Suddenly Obama is anti white and created race divisions and he's a secret Muslim out to create Sharia law.

Trump runs and they fall in line with him.  Everything that isn't kissing Trump's ass is fake news and the world is falling apart and normal people were being pushed aside to allow immigrants and freaks to take over.

My own kid refuses to have anything to do with them anymore.  And they used to be close.  They started criticizing how my kid dressed and looked because it went against how they thought she should look.  She stood up for herself and my parents lost their minds about being disrespected and as her elders, she was obligated to kiss their ass.

Fast forward to the summer of 2020.  Someone they followed or knew apparently saw me and kiddo attending a daytime BLM rally that was literally just  a peaceful march.  This was relayed to my parents and suddenly I'm an antifa terrorist and was probably responsible for the chaos that had unfolded by trouble makers overnight, HOURS after kidlet and I left the rally.  Mom even implied she would turn me in to the police if I didn't fess up.  Of course I told her flat out that we only stayed until 5 or 6 pm and went to get food and go home (had photos to prove this, which is the only reason my mom backed down).

I've been going thru a lot of frustration and confusion.  I still love them and recognize there's some level of brainwashing happening.  I still visit now and again but keep the visits brief and change the subject the moment one of them starts on about whatever the news told them to be mad at.  They've since canceled Fox News after the channel said something negative about their Cheeto Jesus and watch NewsMax exclusively, which seems a million times worse and just throws more fuel onto their hate and rage fire.

I have literally watched my parents pull a complete 180 over the course of 8 1/2 yrs.  And me living my life with the morals they raised me with now means I'm a brainwashed lefty liberal extremists who is just blind to the predator LGBTQ movement (their new boogieman). Of course if I point out that I am living my life and raising my child with the very ideals and morals they raised me with, they rant about how I've twisted their teachings and corrupted my kid (who is almost 20 now) and turned my kid against them.

Sorry this is long.  Just needed to vent it out into the void.  They don't identify with the QAnon movement but they parrot a lot of the Qult's manufactured outrage and conspiracies.
Trying again.

100%|██████████| 12747/12747 [39:58<00:00,  5.31it/s]
100%|██████████| 15615/15615 [00:00<00:00, 177367.14it/s]
 95%|█████████▌| 14897/15615 [42:23<02:58,  4.02it/s]

Error HTTP code 502 from API (<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>

<title> | 502: Bad gateway</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />
</head>
<body>
<div id="cf-wrapper">
    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
                <span class="inline-block">Bad gateway</span>
                <span class="code-label">Error code 502</span>
            </h1>
            <div>
                Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.openai.com" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2026-04-30 09:40:42 UTC</div>
        </header>
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                    <div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Browser

  </h3>

  <span class="leading-1.3 text-2xl text-green-success">Working</span>

</div>
                    <div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&#38;utm_campaign=api.openai.com" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Lyon</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
  <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.openai.com" target="_blank" rel="noopener noreferrer">
    Cloudflare
  </a>
  </h3>

  <span class="leading-1.3 text-2xl text-green-success">Working</span>

</div>
                    <div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">api.openai.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Host

  </h3>

  <span class="leading-1.3 text-2xl text-red-error">Error</span>

</div>
                </div>
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The web server reported a bad gateway error.</p>
                </div>
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                    <p class="mb-6">Please try again in a few minutes.</p>
                </div>
            </div>
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
    <p class="text-13">
      <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">9f459624de5b2785</strong></span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
      <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
        Your IP:
        <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
        <span class="hidden" id="cf-footer-ip">185.25.192.150</span>
        <span class="cf-footer-separator sm:hidden">&bull;</span>
      </span>
      <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&#38;utm_campaign=api.openai.com" id="brand_link" target="_blank">Cloudflare</a></span>

    </p>
    <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
  </div><!-- /.error-footer -->

    </div>
</div>
</body>
</html>) occured for chunk 0 of document 0
valentine
Trying again.

100%|██████████| 15615/15615 [45:14<00:00,  5.75it/s]

Extracting topics...

/Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

UMAP(angular_rp_forest=True, metric='cosine', min_dist=0, n_components=5, n_jobs=1, random_state=42, verbose=True)
Thu Apr 30 11:43:46 2026 Construct fuzzy simplicial set
Thu Apr 30 11:43:46 2026 Finding Nearest Neighbors
Thu Apr 30 11:43:46 2026 Building RP forest with 11 trees
Thu Apr 30 11:43:53 2026 NN descent for 14 iterations
	 1  /  14
	 2  /  14
	 3  /  14
	 4  /  14
	 5  /  14
	Stopping threshold met -- exiting after 5 iterations
Thu Apr 30 11:44:06 2026 Finished Nearest Neighbor Search
Thu Apr 30 11:44:08 2026 Construct embedding

Epochs completed:   6%| ▌          11/200 [00:00]

	completed  0  /  200 epochs

Epochs completed:  16%| █▌         31/200 [00:01]

	completed  20  /  200 epochs

Epochs completed:  26%| ██▌        51/200 [00:01]

	completed  40  /  200 epochs

Epochs completed:  34%| ███▍       69/200 [00:02]

	completed  60  /  200 epochs

Epochs completed:  44%| ████▍      89/200 [00:03]

	completed  80  /  200 epochs

Epochs completed:  55%| █████▍     109/200 [00:03]

	completed  100  /  200 epochs

Epochs completed:  62%| ██████▎    125/200 [00:04]

	completed  120  /  200 epochs

Epochs completed:  74%| ███████▍   149/200 [00:05]

	completed  140  /  200 epochs

Epochs completed:  84%| ████████▍  169/200 [00:05]

	completed  160  /  200 epochs

Epochs completed:  94%| █████████▎ 187/200 [00:06]

	completed  180  /  200 epochs

Epochs completed: 100%| ██████████ 200/200 [00:07]

Thu Apr 30 11:44:16 2026 Finished embedding
Thu Apr 30 11:44:18 2026 Building hub-based search tree
Thu Apr 30 11:44:24 2026 Forward diversification reduced edges from 191205 to 62827
Thu Apr 30 11:44:25 2026 Reverse diversification reduced edges from 62827 to 62827
Thu Apr 30 11:44:27 2026 Degree pruning reduced edges from 79810 to 78059
Thu Apr 30 11:44:27 2026 Resorting data and graph based on tree order
Thu Apr 30 11:44:27 2026 Building and compiling search function

Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

Computing word-topic matrix: 100%|██████████| 21/21 [00:24<00:00,  1.18s/it]
Epochs completed:  27%| ██▋        8/30 [00:00]

	completed  0  /  30 epochs
	completed  3  /  30 epochs
	completed  6  /  30 epochs

Epochs completed:  47%| ████▋      14/30 [00:00]

	completed  9  /  30 epochs
	completed  12  /  30 epochs

Epochs completed:  77%| ███████▋   23/30 [00:01]

	completed  15  /  30 epochs
	completed  18  /  30 epochs
	completed  21  /  30 epochs

Epochs completed:  93%| █████████▎ 28/30 [00:01]

	completed  24  /  30 epochs
	completed  27  /  30 epochs

Epochs completed: 100%| ██████████ 30/30 [00:01]

Describing topics...

100%|██████████| 20/20 [00:52<00:00,  2.62s/it]

In [40]:
print(tm_qan.topic_lis)

[Topic 0: Family Members' Conspiracy Beliefs
, Topic 1: Family Relationships
, Topic 2: Family Relationships
, Topic 3: Alternative Health Remedies
, Topic 4: Vaccine Side Effects
, Topic 5: Media Production.
, Topic 6: Conspiracy Theories
, Topic 7: QAnon Conspiracy Theories
, Topic 8: Conspiracy Theories
, Topic 9: Relationship Dynamics
, Topic 10: Conspiracy Theories
, Topic 11: QAnon Conspiracy Theories
, Topic 12: Family Conflict and Extremism
, Topic 13: QAnon Conspiracy Theories
, Topic 14: QAnon Beliefs and Psychology
, Topic 15: Challenging Beliefs and Behaviors
, Topic 16: Interpersonal Relationships
, Topic 17: Family Members' QAnon Involvement
, Topic 18: Financial Scams
, Topic 19: Emergency Preparedness Supplies
]

A lot of overlapping topics but also very broad?? ('Conspiracy Theories', 'Family Relationships')

In [41]:
print(tm_qan.topic_lis[0].topic_description)

The common topic of the provided words appears to be **conspiracy theories**.

**Aspects and Sub-Topics**:
1. **Beliefs**: Ideas, notions, theories.
2. **Behaviors**: Actions, reactions, responses.
3. **Language**: Slurs, tangents, paragraphs.
4. **Influence**: Radicalizing, deradicalize, influence.
5. **Actions**: Spy, invade, harass.

In [42]:
tm_qan.pprompt("What are the differences and similarities of topic 1 and topic 2?")

GPT wants to the call the function:  {
  "name": "get_topic_information",
  "arguments": "{\"topic_idx_lis\":[1,2]}"
}
Topic 1 and topic 2 both focus on family relationships, but they highlight different aspects within this theme.

Topic 1, "Family Relationships," delves into generational relationships (e.g., paternal, maternal, grandparent), family events (e.g., deathbed, reunions, celebration), inheritance and legacy (e.g., inherited, caretaker, willful), family dynamics (e.g., bickering, shunned, rejects), and family health concerns (e.g., kidneys, hearted, shingles, cancerous).

On the other hand, Topic 2, also named "Family Relationships," emphasizes aspects such as in-laws (e.g., mother-in-law, father-in-law), health and medical issues (e.g., antibody, pancreatic, tumor, breastfeeding), COVID-19 concerns (e.g., maskless, quarantine, vaxer), alternative health practices (e.g., naturopath, vegan, acupuncture), and controversial beliefs and behaviors (e.g., cultic, terrorism, anti-women, conspiracy).

In summary, while both topics revolve around family relationships, Topic 1 centers more on familial dynamics and health concerns within the family, while Topic 2 delves into specific family members and their interactions, health issues, COVID-19 concerns, alternative health practices, and controversial beliefs and behaviors.

{1: "\n            Topic index: 1\n            Topic name: Family Relationships\n            Topic description: The common topic of the provided words seems to be **Family Relationships**. \n\n**Aspects and Sub-Topics**:\n1. **Generational Relationships**: 'paternal', 'maternal', 'granddad', 'grandmas', 'grandparent'.\n2. **Family Events**: 'deathbed', 'reunions', 'celebration', 'burial'.\n3. **Inheritance and Legacy**: 'inherited', 'caretaker', 'dressing', 'willful'.\n4. **Family Dynamics**: 'bickering', 'confuse', 'shunned', 'rejects'.\n5. **Family Health Concerns**: 'kidneys', 'hearted', 'shingles', 'cancerous'.\n            Topic topwords: ['paternal', 'maternal', 'paycheck', 'granddad', 'recording', 'sweetest', 'deathbed', 'bees', 'stations', 'reposts', 'gma', 'download', 'viewing', 'vegan', 'reinstated', 'appalled', 'pressuring', 'processed', 'bfs', 'nicotine', 'ingredients', 'traitors', 'knowledgeable', 'backyard', 'confuses', 'electrical', 'confuse', 'worsened', 'ocean', 'her.', 'coat', 'packaged', 'stethoscope', 'minivan', 'passively', 'measuring', 'arrange', 'prophetic', 'seep', 'tabs', 'interference', 'cream', 'someway', 'overdose', 'celebration', 'receives', 'hysterically', 'mulling', 'ruling', 'blessed', 'kindred', 'dip', 'bashing', 'penny', 'scouring', 'exam', 'coins', 'flow', 'cornered', 'splash', 'bickering', 'heritage', 'mortified', 'tangents', 'opinionated', 'condemned', 'degrade', 'clicked', 'shunned', 'television', 'unknowns', 'birds', 'criticizing', 'mario', 'burdens', 'chiropractors', 'shocks', 'cancerous', 'prolly', 'assistance', 'kidneys', 'props', 'midwest', 'smoker', 'shingles', 'imprisoned', 'toxins', 'hearted', 'marxist', 'net', 'bastard', 'strings', 'emerged', 'jerking', 'separating', 'fascinated', 'remarried', 'salesmen', 'athiest', 'paired', 'pornography', 'propoganda', 'wrath', 'gist', 'cordial', 'networks', 'asinine', 'fists', 'cooperation', 'preached', 'standpoint', 'codependency', 'bucket', 'grandmas', 'grandparent', 'grandpas', 'burial', 'grandmothers', 'unborn', 'caretaker', 'knee', 'mouthpiece', 'casket', 'inherited', 'dressing', 'aunts/uncles', 'processes', 'versa', 'willful', 'keyboard', 'provider', 'iced', 'superficial', 'painfully', 'mins', 'popped', 'intolerable', 'tragically', 'veiled', 'declining', 'owners', 'pushy', 'adamantly', 'hereditary', 'snaps', 'sunshine', 'pouring', 'rejects', 'dust', 'embarassing', 'daughter-in-law', 'burns', 'freezing', 'glimmer', 'reunions', 'deflect', 'cease', 'floodgates', 'hospice', 'cookies', 'coal', 'owning', 'mailed', 'icing', 'glasses', 'circular', 'mixture', 'terminate', 'coke', 'poking', 'automatic', 'spams', 'inundated', 'lightbulb', 'nodding', 'shops', 'baking', 'antimask', 'hurricane', 'ungrateful', 'jobless', 'renewable', 'buffet', 'bagging', 'downloaded', 'reluctantly', 'burner', 'receptive', 'radar', 'weighing', 'centers', 'outfits', 'pitiful', 'overbearing', 'flighty', 'apples', 'bubbling', 'consistent', 'badmouthing', 'nastier', 'popping', 'invade', 'cans', 'refreshments', 'assisted', 'vicinity', 'leak', 'earthers', 'soup', 'robbed', 'binges', 'fined', 'resents', 'notification', 'influx', 'postponed', 'blackouts', 'cloned', 'when/if', 'meals', 'spoonfed', 'burger', 'warns', 'inflating', 'costco', 'enlisted', 'twisting', 'tiring', 'backup', 'gifted', 'bitched', 'minister', 'fricking', 'reception', 'tacky', 'crises', 'lacks', 'registration', 'prophesied', 'worsen', 'generators', 'apprehensive', 'hotels', 'sour', 'eternity', 'robot', 'old-fashioned', 'deed', 'mole', 'hypocrite', 'veneer', 'maskless', 'kooky', 'embarrass', 'blurred', 'android', 'cheaper', 'covid-denier', 'mobility', 'protested', 'rotting', 'candy', 'secondhand', 'graves', 'visitation', 'foretold', 'piling', 'cellphone', 'teetering', 'brunch', 'lawsuit', 'crafts', 'marine', 'arresting', 'crock', 'vocally', 'stacks', 'burgers', 'dissenting', 'tin', 'laughable', 'cigarettes', 'frustrate', 'fiber', 'president-elect', 'electronics', 'discusses', 'criticized', 'danced', 'run-of-the-mill', 'remark', 'woman…', 'blah.', 'sing', 'protects', 'decrying', 'squandered', 'anti-abortion', 'submarine', 'whopping', 'fiscal', 'salads', 'rigid', 'accepts', 'denouncing', 'hysterics', 'anti-maskers', 'visions', 'reconsider', 'noises', 'mold', 'wary', 'buyers', 'co-worker', 'broom', 'nasara', 'unbearably', 'unreal', 'subdivision', 'purple', 'instructed', 'steals', 'hallmark', 'unfiltered', 'knit', 'suspiciously', 'junior', 'marches', 'payment', 'incompetent', 'celebrated', 'printed', 'auction', 'excluding', 'sanctuary', 'roads', 'millionaire', 'falsehoods', 'pronounce', 'tobacco', 'interject', 'co-workers', 'deteriorating', 'reilly', 'get-go', 'muted', 'idol', 'eggs', 'execution', 'phased', 'abundantly', 'millionaires', 'checkbook', 'refugees', 'pentagon', 'amazed', 'crooked', 'reimbursed', 'survives', 'plastered', 'conducting', 'monetary', 'ingredient', 'flesh', 'supervisor', 'units', 'troubled', 'cleared', 'launches', 'tempted', 'scholarship', 'malevolent', 'pocket', 'asses', 'frazzeldrip', 'launched', 'organs', 'mug', 'generals', 'bioweapon', 'venue', 'lawn', 'anti-modern', 'long-winded', 'cleaned', 'pry', 'limbs', 'sea', 'palpable', 'displayed', 'removes', 'b/c', 'lamenting', 'tantrum', 'news.', 'latter', 'display', 'disparage', 'transporting', 'harass', 'rainbows', 'usage', 'clutches', 'terrifies', 'dismisses', 'continent', 'investigated', 'independence', 'nest', 'foreclosure', 'charming', 'ish', 'disclose', 'pin', 'touching', 'gibberish', 'craze', 'counterpoint', 'pressed', 'loophole', 'refuge', 'remembering', 'vortex', 'crazed', 'iffy', 'deteriorate', 'nightly', 'wallets', 'refers', 'casino', 'relay', 'governors', 'tact', 'confederacy', 'redneck', 'reserves', 'behold', 'layered', 'contrast', 'debated', 'double-down', 'prominent', 'snopes', 'marbles', 'uncommon', 'rambles', 'forefront', 'paperwork', 'berating', 'eighth', 'blasting', 'gambled', 'closeted', 'portions', 'unions', 'homosexuals', 'diatribe', 'disliked', 'egregious', 'parrots', 'crashed', 'apathetic', 'respectively', 'imposter', 'disconnecting', 'lamb', 'mistaken', 'accomplished', 'tower', 'disclosure', 'consideration', 'forwarded', 'uphold', 'pivot', 'assigned', 'stalks', 'is…', 'colloidal', 'breakthrough', 'unmarked', 'tongues', 'ecstatic', 'semi-related', 'remembers', 'welp', 'referenced', 'condo', 'poker', 'aswell', 'troubling', 'production', 'plagued', 'circulating', 'broadcasting', 'river', 'delighted', 'hosting', 'spies', 'wildlife', 'happen.']",
 2: '\n            Topic index: 2\n            Topic name: Family Relationships\n            Topic description: The common topic of the provided words seems to be **family dynamics**. \n\n**Aspects and Sub-topics**:\n1. **Family Relationships**: \n   - Inlaws, mother-in-law, father-in-law, daughter-in-law, brother-in-law, grandparent, grandkid.\n2. **Health and Medical Issues**: \n   - Antibody, monoclonal, vertigo, pancreatic, tumor, reproductive, breastfeeding.\n3. **COVID-19 Concerns**: \n   - Maskless, anti-covid, spreader, unmasked, quarantine, vaxer.\n4. **Alternative Health Practices**: \n   - Naturopath, nebulizing, acupuncture, vegan, homemade.\n5. **Controversial Beliefs and Behaviors**: \n   - Cultic, terrorism, anti-mandate, anti-women, conspiracy.\n            Topic topwords: [\'mother-in-law\', \'inlaws\', \'father-in-law\', \'in-law\', \'deployed\', \'antibody\', \'peroxide\', \'bridal\', \'brother-in-law\', \'marrying\', \'monoclonal\', \'vertigo\', \'naturopath\', \'flabbergasted\', \'invaded\', \'sweetest\', \'welcoming\', \'alas\', \'grave\', \'staunchly\', \'coins\', \'adore\', \'cultic\', \'terrorism\', \'daughter-in-law\', \'maskless\', \'grandparent\', \'spreader\', \'anti-covid\', \'fish\', \'boils\', \'travelling\', \'wheelchair\', \'swabs\', \'nebulizing\', \'remarried\', \'dried\', \'diets\', \'pancreatic\', \'wakes\', \'rotting\', \'hesitate\', \'waits\', \'antidepressants\', \'deflects\', \'bummer\', \'tumor\', \'effected\', \'tounge\', \'comfortably\', \'sentences\', \'driveway\', \'knowingly\', \'invitation\', \'eastern\', \'hearings\', \'parrots\', \'tacky\', \'shine\', \'gov\', \'dudes\', \'necklace\', \'requests\', \'potato\', \'scoffing\', \'rolls\', \'specialist\', \'balls\', \'reproductive\', \'biracial\', \'versions\', \'grain\', \'alarmed\', \'proposed\', \'jacket\', \'fraudulent\', \'display\', \'beard\', \'dancing\', \'edition\', \'dirt\', \'craze\', \'execution\', \'units\', \'vids\', \'gifted\', \'shits\', \'that.\', \'saddens\', \'hangs\', \'nap\', \'bound\', \'fearing\', \'turmoil\', \'hosting\', \'blacks\', \'non-white\', \'woo\', \'portrait\', \'far-left\', \'salute\', \'frightening\', \'indicated\', \'knocked\', \'oath\', \'disgusts\', \'formally\', \'happiest\', \'horrid\', \'abstract\', \'brushes\', \'debts\', \'pleasure\', \'supervision\', \'equality\', \'togethers\', \'shithole\', \'assumption\', \'outdoor\', \'badger\', \'watchlist\', \'ridiculed\', \'lingering\', \'retrospect\', \'conveniently\', \'unemployment\', \'enjoys\', \'messes\', \'hosted\', \'vindictive\', \'recommendation\', \'witnessing\', \'satisfaction\', \'diehard\', \'research.\', \'hyper\', \'intensely\', \'mils\', \'bridesmaids\', \'whooping\', \'accidental\', \'unmasked\', \'caretaker\', \'infant\', \'grandsons\', \'grandkid\', \'colleague\', \'burial\', \'malicious\', \'quarantining\', \'grandpas\', \'poke\', \'covid.\', \'elder\', \'epidemiologist\', \'ambulance\', \'bride\', \'nasal\', \'hospitality\', \'intolerable\', \'frail\', \'prognosis\', \'anti-mandate\', \'quarantined\', \'withhold\', \'high-risk\', \'pulse\', \'vitality\', \'breaths\', \'unborn\', \'foaming\', \'preschool\', \'recipient\', \'peanut\', \'adamantly\', \'fertility\', \'surrogate\', \'unvaxed\', \'resistant\', \'infectious\', \'sickened\', \'deathly\', \'breastfeeding\', \'graciously\', \'hamburger\', \'propose\', \'arrange\', \'preventable\', \'avoids\', \'inseparable\', \'vegan\', \'vaxer\', \'sterile\', \'homemade\', \'sickening\', \'infusion\', \'chemist\', \'euthanize\', \'invincible\', \'espouses\', \'bipap\', \'acupuncture\', \'immunized\', \'infections\', \'bronchitis\', \'hearted\', \'viscous\', \'bath\', \'vacations\', \'rouge\', \'surgeon\', \'birthing\', \'burger\', \'mercury\', \'kidney\', \'myocarditis\', \'vacationing\', \'seperate\', \'elders\', \'dietary\', \'espoused\', \'organs\', \'paralyzed\', \'sperm\', \'faux\', \'steroids\', \'kooky\', \'apathetic\', \'administer\', \'cows\', \'contradictions\', \'enrolled\', \'dairy\', \'flavor\', \'dr-\', \'retire\', \'ingredients\', \'euthanized\', \'infusions\', \'arthritis\', \'healthiest\', \'drugstore\', \'indoor\', \'vaccine.\', \'ache\', \'placebo\', \'microscope\', \'microchipping\', \'pediatrician\', \'bandaid\', \'accusation\', \'drip\', \'swallowed\', \'babble\', \'rubbing\', \'salary\', \'carelessness\', \'dizziness\', \'surrounds\', \'freeze\', \'fumes\', \'accommodate\', \'coddle\', \'steroid\', \'flatly\', \'tripped\', \'manufacture\', \'medicines\', \'sinuses\', \'visceral\', \'vomiting\', \'cardboard\', \'injection\', \'temperature\', \'verbatim\', \'prescribes\', \'hugged\', \'sheet\', \'puppy\', \'install\', \'acetaminophen\', \'heels\', \'discharged\', \'tattoo\', \'grilling\', \'versa\', \'tropical\', \'praising\', \'pressured\', \'veterinarian\', \'sheriff\', \'falsely\', \'anti-women\', \'brat\', \'scanner\', \'crazies\', \'horses\', \'bloodwork\', \'sliced\', \'estrangement\', \'yards\', \'dosage\', \'tumors\', \'mutually\', \'jobless\', \'debated\', \'foggy\', \'organ\', \'sunlight\', \'self-imposed\', \'unsolicited\', \'advising\', \'weirdo\', \'fiber\', \'pleaded\', \'trickling\', \'vibrant\', \'inaccurate\', \'pissy\', \'tailspin\', \'cultish\', \'temperatures\', \'unrecognisable\', \'gobbling\', \'unsavory\', \'blanket\', \'vomit\', \'booked\', \'toothpaste\', \'cabin\', \'trustworthy\', \'cleanses\', \'astonished\', \'lemonade\', \'cooky\', \'frank\', \'corporate\', \'postponed\', \'disappearing\', \'tiresome\', \'suckered\', \'soda\', \'worms\', \'ailments\', \'warmer\', \'hotspot\', \'toast\', \'cherry\', \'outed\', \'joint\', \'cooling\', \'plug\', \'ill.\', \'shrugged\', \'speechless\', \'ripe\', \'blindsided\', \'bowl\', \'irritating\', \'butter\', \'fills\', \'bake\', \'crooks\', \'eyed\', \'fuming\', \'coasts\', \'radar\', \'snide\', \'feathers\', \'sheds\', \'jets\', \'b.s\', \'confided\', \'deteriorate\', \'stride\', \'candidacy\', \'reconciliation\', \'lake\', \'falsehoods\', \'aloof\', \'emailing\', \'namely\', \'islands\', \'bout\', \'snakes\', \'deleting\', \'excluding\', \'bullshitting\', \'absorbs\', \'gorgeous\', \'declining\', \'arguements\', \'dungeon\', \'heartedly\', \'grids\', \'urges\', \'chatted\', \'mixture\', \'waved\', \'docs\', \'creature\', \'tweeting\', \'champagne\', \'bleed\', \'family…\', \'unverified\', \'dial\', \'spying\', \'likeminded\', \'shite\', "gov\'t", \'uhh\', \'horseshit\', \'gobsmacked\', \'snowballed\', \'cordial\', \'hollow\', \'fade\', \'expense\', \'regime\', \'factory\', \'poked\', \'plausible\', \'flooding\', \'morons\', \'floored\', \'tolerating\', \'baking\', \'cubes\', \'abyss\', \'prefers\', \'sham\', \'infatuation\', \'centers\', \'snuck\', \'cites\', \'favourite\', \'goodbyes\', \'shaming\', \'skirt\', \'regrets\', \'burner\', \'ungrateful\', \'kindest\', \'whew\', \'invade\', \'viewing\', \'surviving\', \'adjusted\', \'worsened\', \'fuss\', \'businessman\', \'lips\', \'laughable\', \'posture\', \'explode\', \'chuckling\', \'misdirected\', \'incredulous\', \'fleeting\', \'shops\', \'sympathies\', \'copy/paste\', \'adored\', \'marches\', \'stricken\', \'marine\', \'fridge\', \'libertards\', \'overboard\', \'prophesy\', \'technical\', \'lump\', \'excursion\', \'turf\', \'pitted\', \'billion\', \'alpha\', \'invading\', \'unsourced\', \'decorations\', \'bushes\', \'deity\', \'shave\', \'outnumbered\', \'incel\', \'oust\', \'grieved\', \'stances\', \'tales\', \'spirits\', \'pro-choice\', \'contentious\', \'element\', \'secretive\', \'paternal\', \'duration\', \'declares\', \'doubted\', \'tiniest\']'}

It seems like the topics are too broad (one topic covers a lot of different things - both family dynamics and family health among other things) - less try to have more number of topics so that it's more granular?

In [43]:
tm_qan.pprompt("The topics seem too broad and covering a lot of different things at the same time. Can we spread it out to have more number of topics, each with more distinct and granular themes?")

GPT wants to the call the function:  {
  "name": "get_topic_information",
  "arguments": "{\"topic_idx_lis\":[0,1,2,3,4,5,6]}"
}
Expanding the number of topics with more distinct and granular themes is possible by incorporating the following refined topics from the existing broad topics:

1. **Topic 0: Conspiracy Theories and Behaviors**:
   - **Beliefs and Language**: Conspiracism, obsession, slurs.
   - **Behaviors and Influence**: Radicalizing, deradicalize, influence.
   - **Actions**: Spy, invade, harass.

2. **Topic 1: Family Relationships**:
   - **Generational Relationships**: Maternal, paternal, grandparent, grandkid.
   - **Family Events**: Deathbed, reunion, celebration.
   - **Inheritance and Legacy**: Inherited, dressing, willful.

3. **Topic 2: Health and Medical Issues**:
   - **Vaccine Side Effects**: Myocarditis, seizures, headaches.
   - **Safety Concerns**: Aluminum content, effectiveness doubts.
   - **Unproven Treatments**: Homeopathy, herbs, bioweapon fears.

4. **Topic 3: Media Production and Interviewing Ethics**:
   - **Media Production**: Producing, filming, distributing content.
   - **Ethical Considerations**: Fairness, accuracy, sincerity in interviews.
   - **Participant Engagement**: Engaging participants, verifying information.

5. **Topic 4: Environmental Concerns**:
   - **Health Misinformation**: Chem-trails, wildfires, plastic pollution.
   - **Anti-Science Beliefs**: Anti-climate, conspiracy theories, wildfires.

6. **Topic 5: Conspiracy Theories and Misinformation**:
   - **General Misinformation**: Numerology, reptilian, Luciferian.
   - **Health Misinformation**: Naturopathy, bioweapon, biowarfare fears.
   - **Anti-Science Beliefs**: Anti-medicine, anti-masker, anti-vaxxer beliefs.

By diving deeper into these refined topics, we can uncover more nuanced insights and specific narratives related to each distinct theme, providing a more comprehensive understanding of the content within the corpus.

{0: "\n            Topic index: 0\n            Topic name: Family Members' Conspiracy Beliefs\n            Topic description: The common topic of the provided words appears to be **conspiracy theories**. \n\n**Aspects and Sub-Topics**:\n1. **Beliefs**: Ideas, notions, theories.\n2. **Behaviors**: Actions, reactions, responses.\n3. **Language**: Slurs, tangents, paragraphs.\n4. **Influence**: Radicalizing, deradicalize, influence.\n5. **Actions**: Spy, invade, harass.\n            Topic topwords: ['conspiracism', 'files', 'gymnastics', 'enabler', 'chickens', 'salute', 'pro-choice', 'globalist', 'moron', 'fixing', 'legs', 'cornered', 'fascists', 'enslaved', 'insecure', 'players', 'explore', 'slur', 'artists', 'disdain', 'inherently', 'tank', 'invade', 'obsessions', 'cameras', 'shrugged', 'earned', 'coins', 'television', 'fishing', 'validate', 'proposed', 'gaslit', 'consistent', 'fist', 'affair', 'agitated', 'bend', 'hacked', 'suspended', 'wonders', 'carbon', 'man-made', 'criminals', 'enabled', 'dictatorship', 'massively', 'reader', 'reacting', 'predominantly', 'corporate', 'loosing', 'tantrum', 'coffin', 'beforehand', 'appearance', 'encourages', 'lesser', 'misogyny', 'nails', 'in-law', 'cheese', 'wit', 'shits', 'invitation', 'untreated', 'rat', 'enable', 'tracked', 'flawed', 'improved', 'hangs', 'swore', 'baseball', 'brick', 'invaded', 'mountains', 'inferior', 'colored', 'hunt', 'errors', 'backyard', 'brutality', 'dome', 'suspicions', 'row', 'buildings', 'pretends', 'notion', 'clever', 'forgiven', 'insecurities', 'trees', 'tilt', 'pig', 'spamming', 'creators', 'discrimination', 'prejudice', 'paragraph', 'deradicalize', 'perform', 'harassed', 'outwardly', 'refers', 'tangents', 'prominent', 'attitudes', 'professors', 'sinking', 'closeted', 'lectures', 'peddling', 'yards', 'dismisses', 'kidnap', 'factory', 'enjoys', 'borders', 'replying', 'superficial', 'dishes', 'feminism', 'stocks', 'comforted', 'in-person', 'him.', 'erratic', 'nutjob', 'beaten', 'illegally', 'murderers', 'drifted', 'shoved', 'overturn', 'basketball', 'net', 'assassinated', 'contributed', 'foster', 'mania', 'verbatim', 'skipped', 'killers', 'legacy', 'complicit', 'preach', 'dysfunctional', 'baffling', 'homelessness', 'strictly', 'unfounded', 'supremacists', 'tangentially', 'disguised', 'lunatics', 'depths', 'processed', 'liars', 'radicalizing', 'conspired', 'curse', 'orchestrated', 'sincere', 'spy', 'camels', 'unfold', 'primed', 'provoke', 'ramped', 'ditch', 'assumes', 'winger', 'generational', 'settle', 'severity', 'civilization', 'deliver', 'atrocities', 'entertained', 'conceded', 'pyramids', 'qualities', 'magically', 'sarcastic', 'library', 'expectations', 'lecturing', 'caution', 'indulge', 'equality', 'lover', 'ethics', 'introduce', 'troubling', 'shitting', 'unrecognizable', 'paragraphs', 'sets', 'ridicule', 'bearing', 'midst', 'ordinary', 'rocking', 'grievance', 'opiates', 'influential', 'frightening', 'referenced', 'forming', 'cesspool', 'fate', 'parade', 'headlines', 'blessing', 'immense', 'fills', 'semblance', 'relates', 'grudge', 'resulting', 'rioting', 'bioweapon', 'string', 'excusing', 'pressed', 'grandparent', 'revolve', 'vomit', 'motorcycle', 'gasoline', 'adopt', 'literacy', 'pump', 'painfully', 'outlook', 'toilet', 'preparation', 'standards', 'deleting', 'messes', 'non-binary', 'inject', 'storage', 'speeches', 'criticize', 'procedure', 'silently', 'finance', 'tablet', 'sympathize', 'bucks', 'censor', 'tuition', 'dioxide', 'profound', 'devolves', 'outburst', 'argues', 'globalism', 'abuses', 'misogynist', 'repaired', 'stumble', 'rambly', 'steadfast', 'exacerbated', 'shouts', 'mining', 'bailed', 'drivers', 'parallel', 'gray', 'felon', 'dispute', 'fabricated', 'misleading', 'masculinity', 'mechanical', 'engineered', 'origin', 'sized', 'deteriorated', 'condone', 'blinded', 'devote', 'camel', 'unconditionally', 'confessed', 'knees', 'min', 'accurately', 'prompted', 'bug', 'sceptical', 'balls', 'verify', 'unacceptable', 'hmm', 'tirades', 'redneck', 'pissing', 'n-word', 'conscious', 'cap', 'hosted', 'engulfed', 'credentials', 'slap', 'tainted', 'ruins', 'generator', 'hosting', 'chunk', 'cave', 'bastards', 'injustice', 'that.', 'unbelievably', 'subs', 'commie', 'bosses', 'divisive', 'transform', 'dislikes', 'businessman', 'ticks', 'streamer', 'preaches', 'resolve', 'layers', 'demonizing', 'porch', 'printed', 'whites', 'analyze', 'occupy', 'ingrained', 'gathered', 'collected', 'drills', 'objectively', 'dared', 'plotting', 'default', 'deaf', 'contractor', 'raid', 'unloaded', 'myth', 'improving', 'stances', 'espousing', 'picks', 'dignity', 'conspiring', 'pyramid', 'ethnic', 'volatile', 'spam', 'beneath', 'parrots', 'fools', 'commercial', 'homos', 'counters', 'principles', 'rub', 'cryptic', 'conspiracists', 'constitutional', 'photographer', 'explanations', 'grad', 'integrity', 'clarification', 'spiel', 'submit', 'worm', 'yellow', 'punish', 'gambling', 'circus', 'evils', 'distress', 'serves', 'viewers', 'predicament', 'reinforce', 'genetics', 'tickets', 'consequence', 'alongside', 'cussed', 'justifications', 'freshman', 'coaches', 'controversy', 'ridiculousness', 'belittling', 'opens', 'toe', 'pops', 'interpretation', 'bye', 'comparisons', 'hugged', 'smallest', 'collect', 'riled', 'approve', 'bloodline', 'revenge', 'defends', 'dancing', 'newspapers', 'horrifying', 'pivot', 'promising', 'fraction', 'literature', 'steering', 'tore', 'clicked', 'section', 'recommending', 'portrayed', 'bashing', 'devotion', 'railing', 'rationalize', 'floating', 'uncertainty', 'cracks', 'gov', 'enforce', 'fifth', 'eager', 'antics', 'indignation', 'ordeal', 'undocumented', 'pink', 'foreseeable', 'visitation', 'depressive', 'midterms', 'visions', 'eternal', 'judged', 'journal', 'doxxed', 'flaw', 'raises', 'impeachment', 'peacefully', 'grave', 'insinuated', 'latter', 'pumps', 'tempered', 'deflection', 'banging', 'cetera', 'aloud', 'harass', 'robot', 'carries', 'girlfriends', 'ramping', 'par', 'trades', 'affiliated', 'concede', 'gauge', 'demands', 'tapped', 'immoral', 'wary', 'formerly', 'smokes', 'succeed', 'turpentine', 'waters', 'cabinet', 'heartless', 'whistle', 'unreliable', 'weighing', 'reinstated', 'recording', 'generators', 'resolving', 'remembering', 'traumas', 'prep', 'pedophilic', 'witch', 'penalty', 'task']",
 1: "\n            Topic index: 1\n            Topic name: Family Relationships\n            Topic description: The common topic of the provided words seems to be **Family Relationships**. \n\n**Aspects and Sub-Topics**:\n1. **Generational Relationships**: 'paternal', 'maternal', 'granddad', 'grandmas', 'grandparent'.\n2. **Family Events**: 'deathbed', 'reunions', 'celebration', 'burial'.\n3. **Inheritance and Legacy**: 'inherited', 'caretaker', 'dressing', 'willful'.\n4. **Family Dynamics**: 'bickering', 'confuse', 'shunned', 'rejects'.\n5. **Family Health Concerns**: 'kidneys', 'hearted', 'shingles', 'cancerous'.\n            Topic topwords: ['paternal', 'maternal', 'paycheck', 'granddad', 'recording', 'sweetest', 'deathbed', 'bees', 'stations', 'reposts', 'gma', 'download', 'viewing', 'vegan', 'reinstated', 'appalled', 'pressuring', 'processed', 'bfs', 'nicotine', 'ingredients', 'traitors', 'knowledgeable', 'backyard', 'confuses', 'electrical', 'confuse', 'worsened', 'ocean', 'her.', 'coat', 'packaged', 'stethoscope', 'minivan', 'passively', 'measuring', 'arrange', 'prophetic', 'seep', 'tabs', 'interference', 'cream', 'someway', 'overdose', 'celebration', 'receives', 'hysterically', 'mulling', 'ruling', 'blessed', 'kindred', 'dip', 'bashing', 'penny', 'scouring', 'exam', 'coins', 'flow', 'cornered', 'splash', 'bickering', 'heritage', 'mortified', 'tangents', 'opinionated', 'condemned', 'degrade', 'clicked', 'shunned', 'television', 'unknowns', 'birds', 'criticizing', 'mario', 'burdens', 'chiropractors', 'shocks', 'cancerous', 'prolly', 'assistance', 'kidneys', 'props', 'midwest', 'smoker', 'shingles', 'imprisoned', 'toxins', 'hearted', 'marxist', 'net', 'bastard', 'strings', 'emerged', 'jerking', 'separating', 'fascinated', 'remarried', 'salesmen', 'athiest', 'paired', 'pornography', 'propoganda', 'wrath', 'gist', 'cordial', 'networks', 'asinine', 'fists', 'cooperation', 'preached', 'standpoint', 'codependency', 'bucket', 'grandmas', 'grandparent', 'grandpas', 'burial', 'grandmothers', 'unborn', 'caretaker', 'knee', 'mouthpiece', 'casket', 'inherited', 'dressing', 'aunts/uncles', 'processes', 'versa', 'willful', 'keyboard', 'provider', 'iced', 'superficial', 'painfully', 'mins', 'popped', 'intolerable', 'tragically', 'veiled', 'declining', 'owners', 'pushy', 'adamantly', 'hereditary', 'snaps', 'sunshine', 'pouring', 'rejects', 'dust', 'embarassing', 'daughter-in-law', 'burns', 'freezing', 'glimmer', 'reunions', 'deflect', 'cease', 'floodgates', 'hospice', 'cookies', 'coal', 'owning', 'mailed', 'icing', 'glasses', 'circular', 'mixture', 'terminate', 'coke', 'poking', 'automatic', 'spams', 'inundated', 'lightbulb', 'nodding', 'shops', 'baking', 'antimask', 'hurricane', 'ungrateful', 'jobless', 'renewable', 'buffet', 'bagging', 'downloaded', 'reluctantly', 'burner', 'receptive', 'radar', 'weighing', 'centers', 'outfits', 'pitiful', 'overbearing', 'flighty', 'apples', 'bubbling', 'consistent', 'badmouthing', 'nastier', 'popping', 'invade', 'cans', 'refreshments', 'assisted', 'vicinity', 'leak', 'earthers', 'soup', 'robbed', 'binges', 'fined', 'resents', 'notification', 'influx', 'postponed', 'blackouts', 'cloned', 'when/if', 'meals', 'spoonfed', 'burger', 'warns', 'inflating', 'costco', 'enlisted', 'twisting', 'tiring', 'backup', 'gifted', 'bitched', 'minister', 'fricking', 'reception', 'tacky', 'crises', 'lacks', 'registration', 'prophesied', 'worsen', 'generators', 'apprehensive', 'hotels', 'sour', 'eternity', 'robot', 'old-fashioned', 'deed', 'mole', 'hypocrite', 'veneer', 'maskless', 'kooky', 'embarrass', 'blurred', 'android', 'cheaper', 'covid-denier', 'mobility', 'protested', 'rotting', 'candy', 'secondhand', 'graves', 'visitation', 'foretold', 'piling', 'cellphone', 'teetering', 'brunch', 'lawsuit', 'crafts', 'marine', 'arresting', 'crock', 'vocally', 'stacks', 'burgers', 'dissenting', 'tin', 'laughable', 'cigarettes', 'frustrate', 'fiber', 'president-elect', 'electronics', 'discusses', 'criticized', 'danced', 'run-of-the-mill', 'remark', 'woman…', 'blah.', 'sing', 'protects', 'decrying', 'squandered', 'anti-abortion', 'submarine', 'whopping', 'fiscal', 'salads', 'rigid', 'accepts', 'denouncing', 'hysterics', 'anti-maskers', 'visions', 'reconsider', 'noises', 'mold', 'wary', 'buyers', 'co-worker', 'broom', 'nasara', 'unbearably', 'unreal', 'subdivision', 'purple', 'instructed', 'steals', 'hallmark', 'unfiltered', 'knit', 'suspiciously', 'junior', 'marches', 'payment', 'incompetent', 'celebrated', 'printed', 'auction', 'excluding', 'sanctuary', 'roads', 'millionaire', 'falsehoods', 'pronounce', 'tobacco', 'interject', 'co-workers', 'deteriorating', 'reilly', 'get-go', 'muted', 'idol', 'eggs', 'execution', 'phased', 'abundantly', 'millionaires', 'checkbook', 'refugees', 'pentagon', 'amazed', 'crooked', 'reimbursed', 'survives', 'plastered', 'conducting', 'monetary', 'ingredient', 'flesh', 'supervisor', 'units', 'troubled', 'cleared', 'launches', 'tempted', 'scholarship', 'malevolent', 'pocket', 'asses', 'frazzeldrip', 'launched', 'organs', 'mug', 'generals', 'bioweapon', 'venue', 'lawn', 'anti-modern', 'long-winded', 'cleaned', 'pry', 'limbs', 'sea', 'palpable', 'displayed', 'removes', 'b/c', 'lamenting', 'tantrum', 'news.', 'latter', 'display', 'disparage', 'transporting', 'harass', 'rainbows', 'usage', 'clutches', 'terrifies', 'dismisses', 'continent', 'investigated', 'independence', 'nest', 'foreclosure', 'charming', 'ish', 'disclose', 'pin', 'touching', 'gibberish', 'craze', 'counterpoint', 'pressed', 'loophole', 'refuge', 'remembering', 'vortex', 'crazed', 'iffy', 'deteriorate', 'nightly', 'wallets', 'refers', 'casino', 'relay', 'governors', 'tact', 'confederacy', 'redneck', 'reserves', 'behold', 'layered', 'contrast', 'debated', 'double-down', 'prominent', 'snopes', 'marbles', 'uncommon', 'rambles', 'forefront', 'paperwork', 'berating', 'eighth', 'blasting', 'gambled', 'closeted', 'portions', 'unions', 'homosexuals', 'diatribe', 'disliked', 'egregious', 'parrots', 'crashed', 'apathetic', 'respectively', 'imposter', 'disconnecting', 'lamb', 'mistaken', 'accomplished', 'tower', 'disclosure', 'consideration', 'forwarded', 'uphold', 'pivot', 'assigned', 'stalks', 'is…', 'colloidal', 'breakthrough', 'unmarked', 'tongues', 'ecstatic', 'semi-related', 'remembers', 'welp', 'referenced', 'condo', 'poker', 'aswell', 'troubling', 'production', 'plagued', 'circulating', 'broadcasting', 'river', 'delighted', 'hosting', 'spies', 'wildlife', 'happen.']",

In [62]:
import plotly.io as pio
pio.renderers.default = "browser"
# somehow this only runs in browser not in-line
tm_qan.visualize_clusters()

/Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

There is topic splitting but we have to specify what topic exactly we want it to split, and split into what

Again let's revisit the topic list and see what we want to split
Potentially need to be split:
* Topic 0: Family Members' Conspiracy Beliefs
* Topic 1: Family Relationships
* Topic 2: Family Relationships
* Topic 6: Conspiracy Theories
* Topic 7: QAnon Conspiracy Theories
* Topic 8: Conspiracy Theories
* Topic 9: Relationship Dynamics
* Topic 10: Conspiracy Theories
* Topic 11: QAnon Conspiracy Theories
* Topic 12: Family Conflict and Extremism
* Topic 13: QAnon Conspiracy Theories
* Topic 14: QAnon Beliefs and Psychology
* Topic 16: Interpersonal Relationships
* Topic 17: Family Members' QAnon Involvement

Potentially not:
* Topic 3: Alternative Health Remedies
* Topic 4: Vaccine Side Effects
* Topic 5: Media Production.
* Topic 15: Challenging Beliefs and Behaviors
* Topic 18: Financial Scams
* Topic 19: Emergency Preparedness Supplies

In [63]:
tm_qan.prompt("Can you split topics 0, 1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17 into smaller subtopics?")

GPT wants to the call the function:  {
  "name": "split_topic_kmeans",
  "arguments": "{\"topic_idx\":0}"
}

Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

Computing word-topic matrix: 100%|██████████| 1/1 [00:00<00:00,  1.02it/s]
Epochs completed:  16%| █▌         16/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs

Epochs completed:  29%| ██▉        29/100 [00:00]

	completed  20  /  100 epochs
	completed  30  /  100 epochs

Epochs completed:  53%| █████▎     53/100 [00:00]

	completed  40  /  100 epochs
	completed  50  /  100 epochs

Epochs completed:  77%| ███████▋   77/100 [00:01]

	completed  60  /  100 epochs
	completed  70  /  100 epochs

Epochs completed:  95%| █████████▌ 95/100 [00:01]

	completed  80  /  100 epochs
	completed  90  /  100 epochs

Epochs completed: 100%| ██████████ 100/100 [00:01]
Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

100%|██████████| 1/1 [00:04<00:00,  4.05s/it]
Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

Computing word-topic matrix: 100%|██████████| 1/1 [00:00<00:00,  1.49it/s]
Epochs completed:  20%| ██         20/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs

Epochs completed:  45%| ████▌      45/100 [00:00]

	completed  30  /  100 epochs
	completed  40  /  100 epochs

Epochs completed:  61%| ██████     61/100 [00:00]

	completed  50  /  100 epochs
	completed  60  /  100 epochs

Epochs completed:  85%| ████████▌  85/100 [00:01]

	completed  70  /  100 epochs
	completed  80  /  100 epochs

Epochs completed: 100%| ██████████ 100/100 [00:01]

	completed  90  /  100 epochs

Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

100%|██████████| 1/1 [00:02<00:00,  2.92s/it]

GPT wants to the call the function:  {
  "name": "split_topic_kmeans",
  "arguments": "{\"topic_idx\":1}"
}

Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

Computing word-topic matrix: 100%|██████████| 1/1 [00:00<00:00,  2.41it/s]
Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

100%|██████████| 1/1 [00:03<00:00,  3.17s/it]
Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

Computing word-topic matrix: 100%|██████████| 1/1 [00:00<00:00, 26.51it/s]
Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

100%|██████████| 1/1 [00:02<00:00,  2.14s/it]

("For Topic 0, the subtopics identified are:\n1. **QAnon Conspiracy Theories**:\n   - **Paranoia**: Obsessions, man-made, cameras\n   - **False beliefs**: Insecurities, conspiracists, unproven\n   - **Distrust**: Liars, skeptics, bug\n   - **Delusion**: Orchestrated, sinister, lunatics\n   - **Misinformation**: Disguised, misleading, rubbish\n\n2. **Family Relationships**:\n   - **Aggressive behavior**: Fist, Shoved, Brutality\n   - **Discrimination and hate speech**: Misogyny, Homophobia, Racism\n   - **Enabling harmful actions**: Enabler, Validates abuse\n   - **Political beliefs and extremism**: Fascists, Radicalizing\n   - **Social issues and controversies**: Misinformation, Divisive rhetoric\n\nFor Topic 1, the subtopics identified are:\n1. **Family Relationships**:\n   - **Family Dynamics**: Involves terms like 'paternal', 'maternal', 'granddad', 'grandmas', 'grandpas', 'inherited'\n   - **Health Concerns**: Includes words like 'deathbed', 'processed', 'nicotine', 'shingles', 'kidneys\n   - **Inheritance**: Passing down traits or possessions within the family\n   - **Health Issues**: Various health concerns and conditions\n   - **Diet and Lifestyle**: Dietary choices and health-related lifestyle decisions\n   - **Grief and Loss**: Themes of loss and coping with the passing of family members\n\n2. **Family Impact of QAnon**:\n   - **Family Dynamics**: Conflict, manipulation, estrangement\n   - **Health Concerns**: Hospice care, cancer, toxins\n   - **Financial Impact**: Paycheck, lawsuit, burdens\n   - **Emotional Strain**: Intolerable pain, unbearable situation\n   - **Conspiracy Beliefs**: Antimask, radicalized views",
 [Topic 0: Family Members' Conspiracy Beliefs,
  Topic 1: Family Relationships,
  Topic 2: Alternative Health Remedies,
  Topic 3: Vaccine Side Effects,
  Topic 4: Media Production.,
  Topic 5: Conspiracy Theories,
  Topic 6: QAnon Conspiracy Theories,
  Topic 7: Conspiracy Theories,
  Topic 8: Relationship Dynamics,
  Topic 9: Conspiracy Theories,
  Topic 10: QAnon Conspiracy Theories,
  Topic 11: Family Conflict and Extremism,
  Topic 12: QAnon Conspiracy Theories,
  Topic 13: QAnon Beliefs and Psychology,
  Topic 14: Challenging Beliefs and Behaviors,
  Topic 15: Interpersonal Relationships,
  Topic 16: Family Members' QAnon Involvement,
  Topic 17: Financial Scams,
  Topic 18: Emergency Preparedness Supplies,
  Topic 19: Family Relationships,
  Topic 20: Family Impact of QAnon])

(only added 2 new topics after splitting only the first one?)

In [65]:
# if we really want to split we have to do so on every single topic?
tm_qan.topic_prompting.split_topic_hdbscan(topic_idx=1, min_cluster_size=15, inplace=True)

Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

Computing word-topic matrix: 100%|██████████| 1/1 [00:00<00:00,  5.93it/s]
Epochs completed:  70%| ███████    70/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

Epochs completed: 100%| ██████████ 100/100 [00:00]
Epochs completed: 100%| ██████████ 100/100 [00:00]

	completed  0  /  100 epochs
	completed  10  /  100 epochs
	completed  20  /  100 epochs
	completed  30  /  100 epochs
	completed  40  /  100 epochs
	completed  50  /  100 epochs
	completed  60  /  100 epochs
	completed  70  /  100 epochs
	completed  80  /  100 epochs
	completed  90  /  100 epochs

100%|██████████| 1/1 [00:04<00:00,  4.34s/it]

[Topic 0: Family Members' Conspiracy Beliefs,
 Topic 1: Family Relationships,
 Topic 2: Alternative Health Remedies,
 Topic 3: Vaccine Side Effects,
 Topic 4: Media Production.,
 Topic 5: Conspiracy Theories,
 Topic 6: QAnon Conspiracy Theories,
 Topic 7: Conspiracy Theories,
 Topic 8: Relationship Dynamics,
 Topic 9: Conspiracy Theories,
 Topic 10: QAnon Conspiracy Theories,
 Topic 11: Family Conflict and Extremism,
 Topic 12: QAnon Conspiracy Theories,
 Topic 13: QAnon Beliefs and Psychology,
 Topic 14: Challenging Beliefs and Behaviors,
 Topic 15: Interpersonal Relationships,
 Topic 16: Family Members' QAnon Involvement,
 Topic 17: Financial Scams,
 Topic 18: Emergency Preparedness Supplies,
 Topic 19: Family Relationships]

Nothing change?? So confusing

Looking closer at how they actually implemented TopicGPT, it kinda follows the same pipeline as BERTopic: Embeddings -> UMAP (for dim reduc) -> HDBSCAN (for clustering) -> TF-IDF/Centroid Similarity (for finding most representative words/cluster). LLM is just wrapped around this pipeline, being used for initial embeddings, topic summarization, RAG/QA answering & finetuning

So tbh ofc i can rerun and finetune but it'll basically be like with BERTopic, just that this will be more expensive though with the LLM wrapper(s)? Also takes a bit longer to run. And the LLM wrappers are sometimes even buggy,,

# LLooM
Actually let's also just try this
(is it a bit overkill tho?)

In [66]:
!pip install text_lloom

Collecting text_lloom
  Downloading text_lloom-0.8.2.1-py3-none-any.whl.metadata (1.1 kB)
Collecting anywidget<0.10.0,>=0.9.7 (from text_lloom)
  Downloading anywidget-0.9.21-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: hdbscan<0.9.0,>=0.8.33 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from text_lloom) (0.8.42)
Requirement already satisfied: ipywidgets<9.0.0,>=8.1.2 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from text_lloom) (8.1.8)
Requirement already satisfied: jupyterlab_widgets<4.0.0,>=3.0.10 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from text_lloom) (3.0.16)
Requirement already satisfied: nltk<4.0.0,>=3.8.1 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from text_lloom) (3.9.4)
Collecting numba<0.61.0,>=0.60.0 (from text_lloom)
  Downloading numba-0.60.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting openai<2.0.0,>=1.57.0 (from text_lloom)
  Downloading openai-1.109.1-py3-none-any.whl.metadata (29 kB)
Collecting pathos<0.4.0,>=0.3.0 (from text_lloom)
  Downloading pathos-0.3.5-py3-none-any.whl.metadata (11 kB)
Collecting tiktoken<0.8.0,>=0.7.0 (from text_lloom)
  Downloading tiktoken-0.7.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: umap-learn<0.6.0,>=0.5.5 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from text_lloom) (0.5.12)
Collecting yaspin<4.0.0,>=3.0.2 (from text_lloom)
  Downloading yaspin-3.4.0-py3-none-any.whl.metadata (15 kB)
Collecting psygnal>=0.8.1 (from anywidget<0.10.0,>=0.9.7->text_lloom)
  Downloading psygnal-0.15.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.1 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from anywidget<0.10.0,>=0.9.7->text_lloom) (4.15.0)
Requirement already satisfied: numpy<3,>=1.20 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from hdbscan<0.9.0,>=0.8.33->text_lloom) (2.4.4)
Requirement already satisfied: scipy>=1.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from hdbscan<0.9.0,>=0.8.33->text_lloom) (1.17.1)
Requirement already satisfied: scikit-learn>=1.6 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from hdbscan<0.9.0,>=0.8.33->text_lloom) (1.8.0)
Requirement already satisfied: joblib>=1.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from hdbscan<0.9.0,>=0.8.33->text_lloom) (1.5.3)
Requirement already satisfied: comm>=0.1.3 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from ipywidgets<9.0.0,>=8.1.2->text_lloom) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from ipywidgets<9.0.0,>=8.1.2->text_lloom) (9.7.0)
Requirement already satisfied: traitlets>=4.3.1 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from ipywidgets<9.0.0,>=8.1.2->text_lloom) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from ipywidgets<9.0.0,>=8.1.2->text_lloom) (4.0.15)
Requirement already satisfied: click in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from nltk<4.0.0,>=3.8.1->text_lloom) (8.3.3)
Requirement already satisfied: regex>=2021.8.3 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from nltk<4.0.0,>=3.8.1->text_lloom) (2026.4.4)
Requirement already satisfied: tqdm in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from nltk<4.0.0,>=3.8.1->text_lloom) (4.67.3)
Collecting llvmlite<0.44,>=0.43.0dev0 (from numba<0.61.0,>=0.60.0->text_lloom)
  Downloading llvmlite-0.43.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (4.8 kB)
Collecting numpy<3,>=1.20 (from hdbscan<0.9.0,>=0.8.33->text_lloom)
  Downloading numpy-2.0.2-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from openai<2.0.0,>=1.57.0->text_lloom) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from openai<2.0.0,>=1.57.0->text_lloom) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from openai<2.0.0,>=1.57.0->text_lloom) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from openai<2.0.0,>=1.57.0->text_lloom) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from openai<2.0.0,>=1.57.0->text_lloom) (2.13.3)
Requirement already satisfied: sniffio in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from openai<2.0.0,>=1.57.0->text_lloom) (1.3.1)
Requirement already satisfied: idna>=2.8 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from anyio<5,>=3.5.0->openai<2.0.0,>=1.57.0->text_lloom) (3.13)
Requirement already satisfied: certifi in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai<2.0.0,>=1.57.0->text_lloom) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai<2.0.0,>=1.57.0->text_lloom) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<2.0.0,>=1.57.0->text_lloom) (0.16.0)
Collecting ppft>=1.7.8 (from pathos<0.4.0,>=0.3.0->text_lloom)
  Downloading ppft-1.7.8-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: dill>=0.4.1 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from pathos<0.4.0,>=0.3.0->text_lloom) (0.4.1)
Collecting pox>=0.3.7 (from pathos<0.4.0,>=0.3.0->text_lloom)
  Downloading pox-0.3.7-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: multiprocess>=0.70.19 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from pathos<0.4.0,>=0.3.0->text_lloom) (0.70.19)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai<2.0.0,>=1.57.0->text_lloom) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai<2.0.0,>=1.57.0->text_lloom) (2.46.3)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai<2.0.0,>=1.57.0->text_lloom) (0.4.2)
Requirement already satisfied: requests>=2.26.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from tiktoken<0.8.0,>=0.7.0->text_lloom) (2.33.1)
Requirement already satisfied: pynndescent>=0.5 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from umap-learn<0.6.0,>=0.5.5->text_lloom) (0.6.0)
Collecting termcolor<4.0,>=3.2 (from yaspin<4.0.0,>=3.0.2->text_lloom)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: decorator>=4.3.2 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (0.6.3)
Requirement already satisfied: wcwidth in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from jedi>=0.18.1->ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (0.7.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from requests>=2.26.0->tiktoken<0.8.0,>=0.7.0->text_lloom) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from requests>=2.26.0->tiktoken<0.8.0,>=0.7.0->text_lloom) (2.6.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from scikit-learn>=1.6->hdbscan<0.9.0,>=0.8.33->text_lloom) (3.6.0)
Requirement already satisfied: executing>=1.2.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (3.0.1)
Requirement already satisfied: pure_eval in /Users/ngocdoan/opt/anaconda3/envs/qan2/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets<9.0.0,>=8.1.2->text_lloom) (0.2.3)
Downloading text_lloom-0.8.2.1-py3-none-any.whl (162 kB)
Downloading anywidget-0.9.21-py3-none-any.whl (231 kB)
Downloading numba-0.60.0-cp311-cp311-macosx_11_0_arm64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 4.3 MB/s  0:00:00 eta 0:00:01
Downloading llvmlite-0.43.0-cp311-cp311-macosx_11_0_arm64.whl (28.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.8/28.8 MB 3.1 MB/s  0:00:09m0:00:0100:01
Downloading numpy-2.0.2-cp311-cp311-macosx_14_0_arm64.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 4.2 MB/s  0:00:01 eta 0:00:01
Downloading openai-1.109.1-py3-none-any.whl (948 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 948.6/948.6 kB 4.1 MB/s  0:00:00 eta 0:00:01
Downloading pathos-0.3.5-py3-none-any.whl (82 kB)
Downloading tiktoken-0.7.0-cp311-cp311-macosx_11_0_arm64.whl (907 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 907.0/907.0 kB 4.0 MB/s  0:00:00 eta 0:00:01
Downloading yaspin-3.4.0-py3-none-any.whl (21 kB)
Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Downloading pox-0.3.7-py3-none-any.whl (29 kB)
Downloading ppft-1.7.8-py3-none-any.whl (56 kB)
Downloading psygnal-0.15.1-cp311-cp311-macosx_11_0_arm64.whl (567 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 567.8/567.8 kB 3.8 MB/s  0:00:00
Installing collected packages: termcolor, psygnal, ppft, pox, numpy, llvmlite, yaspin, tiktoken, pathos, numba, openai, anywidget, text_lloom
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.4
    Uninstalling numpy-2.4.4:
      Successfully uninstalled numpy-2.4.4
  Attempting uninstall: llvmlite0m━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/13 [numpy]
    Found existing installation: llvmlite 0.47.0━━━━━━━━━━━━━━  4/13 [numpy]
    Uninstalling llvmlite-0.47.0:0m━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/13 [numpy]
      Successfully uninstalled llvmlite-0.47.0━━━━━━━━━━━━━━━━━━━━  5/13 [llvmlite]
  Attempting uninstall: tiktoken╺━━━━━━━━━━━━━━━━━━━━━━━━  5/13 [llvmlite]
    Found existing installation: tiktoken 0.12.0━━━━━━━━━━━━━━  5/13 [llvmlite]
    Uninstalling tiktoken-0.12.0:━━━━━━━━━━━━━━━━━━━━━━━━  5/13 [llvmlite]
      Successfully uninstalled tiktoken-0.12.0━━━━━━━━━━━━━━━━  5/13 [llvmlite]
  Attempting uninstall: numba━━━━━━━━━━━━━━━━━━━━━━━━  5/13 [llvmlite]
    Found existing installation: numba 0.65.1━━━━━━━━━━━━━━━━━  5/13 [llvmlite]
    Uninstalling numba-0.65.1:[0m━━━━━━━━━━━━━━━━━━━━━━━━  5/13 [llvmlite]
      Successfully uninstalled numba-0.65.1━━━━━━━━━━━━━━━━━━━  5/13 [llvmlite]
  Attempting uninstall: openai━━━━━╸━━━━━━━━━━━━  9/13 [numba]
    Found existing installation: openai 0.28.1[90m━━━━━━━━━━━━  9/13 [numba]
    Uninstalling openai-0.28.1:╸━━━━━━━━━━━━  9/13 [numba]
      Successfully uninstalled openai-0.28.1m━━━━━━━━━━━━  9/13 [numba]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/13 [text_lloom]3 [text_lloom]
Successfully installed anywidget-0.9.21 llvmlite-0.43.0 numba-0.60.0 numpy-2.0.2 openai-1.109.1 pathos-0.3.5 pox-0.3.7 ppft-1.7.8 psygnal-0.15.1 termcolor-3.3.0 text_lloom-0.8.2.1 tiktoken-0.7.0 yaspin-3.4.0

In [1]:
import text_lloom.workbench as wb

In [ ]:
# this is a bit dumb but the code requires this specific var name
os.environ["OPENAI_API_KEY"] = os.environ.get("DLAB_OPENAI_KEY")

In [ ]:
# this framework needs the newer version of openai
# !pip install --upgrade openai

In [ ]:
l = wb.lloom(
    df=df_post,
    text_col="selftext",
    #synth_model="gpt-4o-mini",
    # id_col="your_doc_id_col",  # Optional
    # By default, when not specified, uses the following models:
    # - distill_model: gpt-4o-mini
    # - cluster_model: text-embedding-3-large
    # - synth_model: gpt-4o
    # - score_model: gpt-4o-mini
)

No `id_col` provided. Created an ID column named 'id'.

In [ ]:
cur_seed = None 
await l.gen(seed=cur_seed)

N sentences: Median=15, Std=18.47
Auto-suggested parameters: {'filter_n_quotes': 12, 'summ_n_bullets': 9, 'synth_n_concepts': 6}


Estimated cost: $12.34
**Please note that this is only an approximate cost estimate**


Action required


Distill-filter
⠙ Loading ERROR json_load on: {
    "relevant_quotes": [
        "My mom has severe anxiety and depression, as do my siblings.",
        "Our whole childhood revolved around bible teachings of end times and how our church was the only thing holding our country together.",
        "My sister is very depressed.",
        "I will never NOT act if someone might be su\*cidal.",
        "She was raised to think as though she can never amount to anything [without a man] and we are near the 'end times.'",
        "That’s a lot to bear if you are crazy enough to believe it.",
        "I tried my best to talk her up and try and find some sort of spark to get her to try and LIVE life.",
        "None of them reach out, unless they need something of me.",
        "I feel as though I am a distant parent to my Qfam.",
        "Add on all of the deep state propaganda and everything that goes with that and we have a very rocky relationship.",
        "I feel as though whole thing feels phony because they aren’t telling me the 'truth' and I can’t be open with them about my life.",
        "I try to be encouraging and positive, but it is like talking to a stump."
    ]
}
⠹ Loading ERROR json_load on: {
    "relevant_quotes": [
        "I desperately want to know why they ghost - even when you do *everything* to never challenge them or expose your unwashed brain?",
        "She ghosted me 1 year ago, but it's really hitting me hard right now because of some difficult life-stuff rough/emotional hurdles happening-",
        "All I can think is how this kind of deep-dark-sad stuff *is the best friend stuff* - where one of you sobs into the phone and the other hears you out before somehow making you burst out laughing through the tears with a quick quip, then you both slowly move on to some stupid game-planning a solution.",
        "I feel like my other half was murdered by Q.",
        "I love~~(d)~~ her so much that I never called her Q-ing out.",
        "I played the part- I told myself (& anyone who questioned me) that I knew she would do the same for me, that I will wait for her to come back around -",
        "When she would mention crazy s\*\* I would play dumb (& quite well) - and use phrases like 'oh, I'll have to look into that,' etc. so that we could move on to the fun stuff that had nothing whatsoever to do with politics or health.",
        "Not even once-- *she* ghosted *me.*",
        "I didn't even know... we went from planning out our visits and going to a mutual friend's wedding together, talking every week to... she's not picking up the phone..",
        "her brother told me 'she probably thinks you're toxic, impeding her energy growth, just like everyone else is' (they hadnt got on for some time bc of Q)-- but, how? why? I was neutral.. I don't get it.",
        "My heart's breaking into a million pieces today because I miss having my best friend.",
        "I've emailed her, I've texted her... I randomly still do... knowing she's likely blocked me and it's just sitting in a burn-after-reading temp server somewhere out in the ether."
    ]
}
⠸ Loading ERROR json_load on: {
    "relevant_quotes": [
        "A close friend has been through a lot of trauma this year, and she's got PTSD and raw nerves from two near deaths in her family.",
        "Some 'friends' are hitting her with Q crap while she's down.",
        "she confided in me this week she's afraid to get herself and her kids vaccinated because she worries about the government and the virus.",
        "This is a highly intelligent person who is a college teacher, and under normal circumstances she would have the energy to research and fight back.",
        "She's clinging to her own sanity by a thread right now.",
        "I went through trauma myself recently and I told her some of the goofy things I was believing.",
        "That hit a chord with her, and she decided to get off Facebook for the week.",
        "Yesterday she texted me a photo of her vaccine appointment for today.",
        "I'm so very proud of her, and I'm sending her messages of support for the next hour.",
        "Two other people I've known for a long time recently succumbed to the Q-pit, so I'm very glad I was able to rescue this one!!",
        "she kept saying, 'F\*\*K Qanon and their stupid fear tactics! Tell me another joke!'",
        "It feels like I'm flipping a giant bird to Q today!!"
    ]
}
⠴ Loading ERROR json_load on: {
    "relevant_quotes": [
        "I told my mother that we were done for multiple reasons (mostly her anger) after my second child was born in 2019.",
        "She’s always been suckered into conspiracy theories and definitely was into Q at the time.",
        "She tried to contact me once in 2020 to tell me about how Covid was fake and I shut her down then.",
        "I don't want to fight nor argue with you, ok.",
        "We ALL have been lied too- whether You believe this or not.",
        "I'm not "here" to brag... but the "old guard" is going to fall.",
        "IF IF you have any money in saving -401k's etc please move them into gold/silver real assets.",
        "I'm not expecting a reply - just know even though - what has transpired you're still my daughter.",
        "Please watch- let it sink in.",
        "Whether you know it or not - a "sting" operation is taking place and the old guard is going to fall.",
        "She has no other savings I know of and if I had to guess she’s probably blown through her inheritance from my grandparents on this crap.",
        "I know one day I will get a call or visit from an LEO because someone found her body."
    ]
}
ERROR json_load on: {
    "relevant_quotes": [
        "Having a low day.",
        "Separated from my Q husband in the fall.",
        "Been doing everything in my power to lay the ground work for my preschooler to have the tools for critical thinking skills when they come to that stage of development in a few years.",
        "I keep open conversations and never say what their dad is saying is wrong.",
        "Sitting here in tears as my kid naps on me because a few minutes ago they saw contrails in the sky and they explained to me how they are bad and poisoning the air we are breathing.",
        "I gently explained that they are man made clouds from hot meeting cold like when the car exhaust makes clouds in the winter.",
        "I know critical thinking skills are not a thing at this age.",
        "This is going to be a battle all my child's life.",
        "I'm scared that I am not doing enough or that I won't be enough to keep my child sane and kind.",
        "It's hard not to stress and worry about their mind being poisoned with all this Q nonsense.",
        "This is a hard age when their world is so small and they get all their information through mom and dad.",
        "I try to calm myself with 'they believe in easter bunny and santa the stuff their dad "teaches" too will fade.'"
    ]
}
⠇ LoadingERROR json_load on: {
    "relevant_quotes": [
        "He constantly, and I mean constantly, talks about how they are making everything digital so they can have us as their slaves.",
        "he loves to talk about how one day (in the next 5 years) we will be like China with their ID system",
        "the elites will control how we spend our money",
        "if we rebel against them, they will just erase us and take away our money",
        "as it will be all digital.",
        "He is also obsessed with pe\*\*philia",
        "is convinced the elites are sacrificing babies",
        "apparently there is a whistleblower who talked about it.",
        "I just cant listen to him anymore.",
        "Thankfully he is moving out in a few days",
        "my father is so far gone.",
        "He is absolutely and totally convinced in the next 5 years we will become slaves and we will turn into China."
    ]
}
ERROR json_load on: {
    "relevant_quotes": [
        "My fear of my soon-to-be-fiance drinking the Q-Koolaid has influenced me to finally create an account.",
        "He is wonderful, and I have always loved his family- but his mom has recently become really wrapped up in the QAnon stuff.",
        "I get links sent to my phone everyday about how COVID-19 is a hoax, John Legend is a child trafficker (even got a snap of him wearing red shoes in a commercial to prove it!), etc.",
        "It deeply upsets me because before the pandemic, she was not like this.",
        "My boyfriend's brothers have even started keeping their kids from her because of how bad things have gotten.",
        "When I try to explain why the Save Our Children crap is nonsense, I seem like an asshole who supports child abuse/sex trafficking.",
        "I am worried my boyfriend may secretly be into QAnon as well.",
        "He's always been into conspirary theories, but it's always seemed harmless.",
        "Then the other day he told me he thinks JFK Jr. is still alive, which I know is being touted by QAnon.",
        "I do have a little hope because on Sat. we had his parents over for dinner and his mom told us Don Lemon was really dead while we were watching CNN.",
        "he told her she was full of \*\*\*\*.",
        "I just know she is starting to really lose her grip on reality."
    ]
}
⠋ LoadingERROR json_load on: {
    "relevant_quotes": [
        "I just want a space to express myself",
        "I don't have anyone else to share o express",
        "my wife is getting so interested in LGBT topics",
        "I considered myself a neutral person in those topics",
        "she spends a lot of time on his cellphone listening to the opinion of different 'leaders' on the topic",
        "I answered with just no or yes",
        "she turned it against me",
        "she made me feel like sh$\^t",
        "she literally call me, when I'm working just to tell me if I agree or disagree",
        "I didn't know what to answer",
        "my answers right now are just turning in fake support to her point of view",
        "I've seen the harm of social media and what conspiracy theories can do to families"
    ]
}
⠸ Loading ERROR json_load on: {
    "relevant_quotes": [
        "I have a sister (41) who has gone down the Q rabbit hole, we have had more and more arguments recently and just had a pretty massive one and things are not looking good for our relationship.",
        "My sister started spending a lot of time on Facebook during the 2012 election, posting racist memes about Obama and whenever our parents, other siblings or I tried to discuss politics, she’d just say we needed to turn off CNN and would be incredibly defensive.",
        "Things really started to get tense when Trump first declared his run for President, my sister was one of his original supporters, back when everyone thought he was just running for fame, like June 2015-ish.",
        "Her oldest child (who was in 5th grade at the time) got in trouble at school after she was being homophobic to a boy in her class.",
        "Once Trump got elected, my sister became 10 times worse.",
        "Her house is basically a shrine to Trump, Marjorie Taylor Greene and a few other Republican officials and conservative movements.",
        "Recently, my sister has been listening to Paula White and other pastors in Trump’s orbit.",
        "Over the past year, she’s become more and more into QAnon and is constantly sending me links to stuff like 'watch out for this hidden pe\*o logo' and how Trump is going to reveal himself as President.",
        "First off, my 15 y/o nephew told me that my sister had become one of those people who hands out Evangelical pamphlets on Halloween.",
        "She sent me a bunch of links to websites that talked about Q.",
        "I told her I would consider it and she tried to guilt me by saying 'I just want what’s best for you and your husband and my nephews and nieces'.",
        "I want to stay in touch with her, she’s my sister and I love her but it’s becoming increasingly difficult."
    ]
}
⠦ Loading ERROR json_load on: {
    "relevant_quotes": [
        "I have a friend who I care about immensely who just seemed to flip overnight.",
        "She was adamantly a leftist who brought her kids to BLM rallies and women's marches.",
        "I am not sure how deep she has gone down the Q rabbit hole, but what I do see is a lot of Anti-vax wellness propaganda.",
        "Strange thing is when I speak to her on the phone she seems on the fence about things.",
        "One minute she hates feminism, but next minute she is against the patriarchy.",
        "The criticism I saw her give of feminism was something that is not even a part of the ideology of feminism.",
        "That is complete donkey S#!\^!",
        "Well I found out about something called QAnon light which was specifically meant to reach out to women and does so through the Wellness community.",
        "So I asked for some advice from a friend of mine who has done work to help de-radicalize people who have been taken by white supremacist groups.",
        "The advice I was given was thus:",
        "Check in with her from time to time. Ask her how she is doing. Ask how things are with her family.",
        "I think this might just be a phase with her, but there is no way I can know for sure."
    ]
}
⠋ Loading ERROR json_load on: {
    "relevant_quotes": [
        "I thought I finally had an unspoken rule that my parents should never talk about politics around me",
        "my dad broke that when he tried telling me that the lab in Wuhan where they made covid was moved to Ukraine",
        "that's why Russia invaded",
        "I've been on Zoloft for about a month",
        "which finally allowed me to straight up tell him he sounds like an absolute cr\*\*\*head",
        "without my heart rate changing at all",
        "I know that's not how we're supposed to talk with them",
        "but I'm a human and this has been building up for years",
        "It felt good",
        "He had a meltdown and I don't know how I'm supposed to feel",
        "I know the rest of my family is going to side with him",
        "I'm proud of myself for not putting up with it anymore"
    ]
}
⠦ Loading ERROR json_load on: {
    "relevant_quotes": [
        "I have been struggling to put into words how I feel about what is happening to my mother.",
        "I have been mostly in my room trying to block it out, but I have to hear it every time I come out.",
        "I don't care if you burn with your sick ideas, you stay the f\*\*k away from my Star Wars.",
        "I feel that we are living in the midst of an historic schism not seen since the Great Christian Schism of 1054.",
        "The 'religion' that my mom, and other likeminded Q's follow is beginning to take on the guise of a fundamentalist terrorist organization.",
        "I think this cult is killing my love for my mother....and I worry about the consequences of those emotions.",
        "I wish she listened to ANYTHING else...call me stupid, but I wish my mother liked dramas.",
        "Now I just feel stupid for thinking she'll be anything but a devoted follower of Q.",
        "I want to hear what y'all think about this sense of empathetic void for people just totally gone for this cult.",
        "I want to cry, but I feel unable to do so.",
        "I unfortunately do not know the dosage she is using, as she has adopted a petty defensive stance on my prying into her taking care of the dogs.",
        "I am choosing to keep an eye on the dogs for any signs of discomfort, or reaction to an overdose based on the symptoms some of y'all mentioned are likely to occur."
    ]
}
⠋ Loading ERROR json_load on: {
    "relevant_quotes": [
        "My father has been into this canon stuff for \~6 months (started when the election cycle was heating up).",
        "On a daily basis I'm getting sent these outrageously stupid conspiracies by my dad and I'm really confused how any human could believe them.",
        "losing the last and only person left in my immediate family has just taken a toll on me.",
        "The last time I saw my dad is when I was home on Christmas break and told my dad that I didn't think the election was rigged; This enraged him.",
        "I went to the gym and came home to a bag of my clothes left on the porch and a suitcase with my laptop and chargers in it.",
        "Needless to say, I took a long drive back to my university apartment that night and haven't been back since.",
        "today my dad sent me photos of the sky with the white trails that typically follow behind planes and wrote this whole paragraph about how the government is trying to block the sun so people can't grow food.",
        "This is just one of the many crazy conspiracies that he's texted me, but it stood out to me more than the rest.",
        "For him to look in the sky and see the same plane trails he always seen since he was a kid, but now being convinced that the condensation is a government plan is sickening and delusional.",
        "He responds with 'That's fake news' or 'That's what they want you to think' whenever I provide science based counter evidence to his insane claims.",
        "Do I contact a medical professional?",
        "I'm 20 and I feel a bit nervous entering the real world soon after college with no help or family."
    ]
}
⠹ Loading ERROR json_load on: {
    "relevant_quotes": [
        "Lifelong R voter, she actually got me in 2016 and I voted for Trump over the next couple years our politics swung apart as I started college, and I started thinking for myself (familiar story to many of you I’m sure).",
        "I voted for Biden in 2020 and now I’m in her shit book.",
        "She normally works remote, but she had to go in office this week so I’m at home dog sitting my/our dog since he is old and needs someone to watch after him.",
        "She came storming in from work complaining about how stupid all her coworkers are and how much she hates her job which is pretty standard affair.",
        "I was doing some work (I got the week remote so I could dog sit) when she came in and began scrolling twitter before declaring 'you must be having a pretty good day since Trump is guilty'.",
        "I told her I didn’t really care but she kept pestering me about it saying some not very nice things about Kamala Harris and the like.",
        "Finally, she said, 'They are already setting up a ‘conservative’ to shoot up a pride parade so they can move to the next stage of the plan.'",
        "I had enough at this point, so I asked her, 'what are you going to do about it?'",
        "She said, 'nothing, there’s nothing I can do.'",
        "This is where I went too far and snapped at her, 'then you should shut the f\*\*k up about it. Why are you even complaining if you aren’t going to do anything about it.'",
        "She actually agreed with me (sarcastically) before getting up and storming off upstairs presumably to text her friends how horrible I am.",
        "Though I’m not going to her, I’m in the kitchen and near the only bathroom so she’ll be forced to interact with me at some point."
    ]
}
⠸ Loading ERROR json_load on: {
    "relevant_quotes": [
        "My mother isnt quite Q anymore but more aligned now, but all this started with Q.",
        "She recently had a panic attack and went to the hospital because we had no clue what was going on.",
        "Shes alright now, but she was writing in a book when she had her attack.",
        "I skimmed through a few of the pages and its rough, shes on about how much she hates living here.",
        "how discussed she is in my dad for not following her same beliefs and becoming 'emotionally Enlighted'",

          id                                           selftext
0          0  What an evil, horrible and vile think so many ...
1          1  Divorce is difficult situation generally, but ...
2          2  Five years ago when Trump began his campaign I...
3          3  hi, just using my throwaway to rant a little b...
4          4  What is the best source for Q-Anon.\nI need to...
...      ...                                                ...
12718  12742  Well, they have to do that in order to red pil...
12719  12743  both my adult children are complete conspiracy...
12720  12744  HE didn't mean it like that\nI don't care abou...
12721  12745  ⚠️ TRIGGER WARNING: Domestic abuse, child abus...
12722  12746  My mother was raised in Alabama.\nShe lives wa...

[12723 rows x 2 columns]

Distill-summarize
✅ Done

           id                                       selftext
0           0                 Evil and fear in QANON beliefs
1           0  Personal journey towards independent thinking
2           0                      WWJD applied to real life
3           0     QANON followers as victims of manipulation
4           0        Family struggles due to QANON influence
...       ...                                            ...
114503  12746       Belief that housing will tip state blue.
114504  12746  Questioning the timeline of government plans.
114505  12746  Husband saw suspicious ballots on interstate.
114506  12746     Doubts about election integrity and votes.
114507  12746  Feeling of distance due to political beliefs.

[114508 rows x 2 columns]

Cluster
⠇ Loading

IOStream.flush timed out

⠙ Loading

python(43190) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

⠏ Loading

python(43212) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43213) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python(43214) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

⠋ Loading

python(43215) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

⠙ Loading

python(43216) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

⠙ Loading

(oopsi hope $12 is not a lot)

(and it's taking quite long)

but then this highlights a potential drawback to using LLooM - that it can be quite expensive to finetune (if we want to rerun with alternative hyperparameters or setups), at the scale of ~12.8K long-text (or medium-text) documents - for BERTopic we can always rerun (which we did a lot) cuz it's fast and free)

update: it's freaking my computer out!? and it's been running for ~1.5hours so i'll stop it here (maybe can try again on the server or sth but idk)

(i hope i didn't burn more than $12)

The part below was not executed because the earlier part failed to finish

In [ ]:
l.summary()

In [ ]:
l.select()

In [ ]:
l.show_selected()

In [ ]:
# Run concept scoring
score_df = await l.score()